### ISSUE TITLE
Change Data Types

### ISSUE THREAD

**Issue by xorz57** [xorz57/forest#115]
## Task List
- [x] Change `height` from `unsigned` to `int`
- [x] Change the return value types of `balance(...)` and `height(...)` to `auto`
- [x] Change the return value type of `size(...)` to `auto`
